version: 2
jobs:
  spellcheck:
    docker:
      - image: ruby:2.3.5

    working_directory: /root/clojure-by-example

    steps:
      - checkout

      - run: apt-get -q update; apt-get -y install libgmp3-dev aspell-en curl

      - run: cp .aspell.en.pws /root/

      - restore_cache:
          keys:
            - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle

      - run: bundle exec rake spellcheck

  deploy:
    docker:
      - image: ruby:2.3.5

    working_directory: /root/clojure-by-example

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3c:7f:69:15:05:8b:9b:1a:0b:d6:2e:5e:75:9d:7c:70"

      - checkout

      - restore_cache:
          keys:
            - projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
          - vendor/bundle

      - deploy: 
          command: |
            git config --global user.email "kimh-machine1@kimh.33mail.com"
            git config --global user.name "kimh-machine1"
            git remote remove origin
            git remote add origin git@github.com:kimh/clojure-by-example.git
            bundle exec rake publish commit_message_suffix="[ci skip]"

workflows:
  version: 2
  spellcheck_and_deploy:
    jobs:
      - spellcheck
      - deploy:
          requires:
            - spellcheck
          filters:
            branches:
              only: master
